version: '3'
services:
  opensearch-node1:
    image: opensearch-kuromoji:latest
    container_name: opensearch-node1
    environment:
      - "discovery.type=single-node"
      - bootstrap.memory_lock=false
      - "DISABLE_SECURITY_PLUGIN=true"
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    volumes:
      - opensearch-data1:/usr/share/opensearch/data
    ports:
      - 9200:9200
      - 9600:9600
    networks:
      - opensearch-net # All of the containers will join the same Docker bridge network

volumes:
  opensearch-data1:

networks:
  opensearch-net:
